package com.sc.sis.model;

public class AuthUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.id
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.user_name
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_user.passwd
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    private String passwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.id
     *
     * @return the value of auth_user.id
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.id
     *
     * @param id the value for auth_user.id
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.user_name
     *
     * @return the value of auth_user.user_name
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.user_name
     *
     * @param userName the value for auth_user.user_name
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_user.passwd
     *
     * @return the value of auth_user.passwd
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_user.passwd
     *
     * @param passwd the value for auth_user.passwd
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd == null ? null : passwd.trim();
    }
}