package com.sc.sis.model;

public class PointData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_data.id
     *
     * @mbg.generated Sun Feb 19 11:06:37 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_data.poin_name
     *
     * @mbg.generated Sun Feb 19 11:06:37 CST 2017
     */
    private String poinName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_data.unit
     *
     * @mbg.generated Sun Feb 19 11:06:37 CST 2017
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column point_data.remark
     *
     * @mbg.generated Sun Feb 19 11:06:37 CST 2017
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_data.id
     *
     * @return the value of point_data.id
     *
     * @mbg.generated Sun Feb 19 11:06:37 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_data.id
     *
     * @param id the value for point_data.id
     *
     * @mbg.generated Sun Feb 19 11:06:37 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_data.poin_name
     *
     * @return the value of point_data.poin_name
     *
     * @mbg.generated Sun Feb 19 11:06:37 CST 2017
     */
    public String getPoinName() {
        return poinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_data.poin_name
     *
     * @param poinName the value for point_data.poin_name
     *
     * @mbg.generated Sun Feb 19 11:06:37 CST 2017
     */
    public void setPoinName(String poinName) {
        this.poinName = poinName == null ? null : poinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_data.unit
     *
     * @return the value of point_data.unit
     *
     * @mbg.generated Sun Feb 19 11:06:37 CST 2017
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_data.unit
     *
     * @param unit the value for point_data.unit
     *
     * @mbg.generated Sun Feb 19 11:06:37 CST 2017
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column point_data.remark
     *
     * @return the value of point_data.remark
     *
     * @mbg.generated Sun Feb 19 11:06:37 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column point_data.remark
     *
     * @param remark the value for point_data.remark
     *
     * @mbg.generated Sun Feb 19 11:06:37 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}