/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sc_rtdb_RealTimeDBDao_PointData */

#ifndef _Included_com_sc_rtdb_RealTimeDBDao_PointData
#define _Included_com_sc_rtdb_RealTimeDBDao_PointData
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
