/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sc_rtdb_RealTimeDBDao */

#ifndef _Included_com_sc_rtdb_RealTimeDBDao
#define _Included_com_sc_rtdb_RealTimeDBDao
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sc_rtdb_RealTimeDBDao
 * Method:    HelloWorld
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sc_rtdb_RealTimeDBDao_HelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     com_sc_rtdb_RealTimeDBDao
 * Method:    SC_InitialEnv
 * Signature: (Ljava/lang/String;SLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_sc_rtdb_RealTimeDBDao_SC_1InitialEnv
  (JNIEnv *, jobject, jstring, jshort, jstring, jstring);

/*
 * Class:     com_sc_rtdb_RealTimeDBDao
 * Method:    SC_UninitialEnv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sc_rtdb_RealTimeDBDao_SC_1UninitialEnv
  (JNIEnv *, jobject);

/*
 * Class:     com_sc_rtdb_RealTimeDBDao
 * Method:    SC_CheckServiceStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_sc_rtdb_RealTimeDBDao_SC_1CheckServiceStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_sc_rtdb_RealTimeDBDao
 * Method:    SC_GetRTPoint
 * Signature: (Ljava/lang/String;)Lcom/sc/rtdb/PointData;
 */
JNIEXPORT jobject JNICALL Java_com_sc_rtdb_RealTimeDBDao_SC_1GetRTPoint__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sc_rtdb_RealTimeDBDao
 * Method:    SC_GetRTPointFull
 * Signature: (Ljava/lang/String;)Lcom/sc/rtdb/PointData;
 */
JNIEXPORT jobject JNICALL Java_com_sc_rtdb_RealTimeDBDao_SC_1GetRTPointFull__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sc_rtdb_RealTimeDBDao
 * Method:    SC_GetRTPoint
 * Signature: ([Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_sc_rtdb_RealTimeDBDao_SC_1GetRTPoint___3Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_sc_rtdb_RealTimeDBDao
 * Method:    SC_GetRTPointFull
 * Signature: ([Ljava/lang/String;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_sc_rtdb_RealTimeDBDao_SC_1GetRTPointFull___3Ljava_lang_String_2
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
