package com.sc.sis.mapper;

import com.sc.sis.model.AuthUser;
import com.sc.sis.model.AuthUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    long countByExample(AuthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    int deleteByExample(AuthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    int insert(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    int insertSelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    List<AuthUser> selectByExample(AuthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    AuthUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    int updateByExampleSelective(@Param("record") AuthUser record, @Param("example") AuthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    int updateByExample(@Param("record") AuthUser record, @Param("example") AuthUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    int updateByPrimaryKeySelective(AuthUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auth_user
     *
     * @mbg.generated Sat Feb 18 14:40:44 CST 2017
     */
    int updateByPrimaryKey(AuthUser record);
}